server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: false
spring:
  profiles: dev
  application:
    name: consumer-10001
logging:
  level: debug
---
server:
  port: 10002
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: false
spring:
  profiles: prod
  application:
    name: consumer-10001
logging:
  level: debug
---
server:
  port: 10003
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: false
spring:
  profiles: beta
  application:
    name: consumer-10001
logging:
  level: debug